stages:

  preprocess:
    cmd: python -m src.data.preprocess data/raw/train_file.xlsx models/preprocess_model.pkl data/processed/train_df.pkl
    deps:
      - src/data/preprocess.py
      - src/data/preprocess_.py
      - data/raw/train_file.xlsx
    outs:
      - models/preprocess_model.pkl
      - data/processed/train_df.pkl

  train:
    cmd: python -m src.model.train data/processed/train_df.pkl models/model.pkl
    deps:
      - src/model/train.py
      - src/model/train_.py
      - data/processed/train_df.pkl
    outs:
      - models/model.pkl