stages:

  preprocess:
    cmd: python -m src.data.preprocess data/raw/train_file.xlsx data/processed/preprocess_model.pkl data/processed/train.pkl
    deps:
      - src/data/preprocess.py
      - src/data/preprocess_.py
      - data/raw/train_file.xlsx
    outs:
      - data/processed/train.pkl

  train:
    cmd: python -m src.model.train data/processed/train.pkl data/processed/model.pkl
    deps:
      - src/model/train.py
      - data/processed/train.pkl
    outs:
      - data/processed/model.pkl