stages:

  preprocess:
    cmd: python -m src.data.preprocess data/raw/train_file.xlsx data/processed/preprocess_model.pkl data/processed/train.pkl
    deps:
      - src/data/preprocess.py
      - data/raw/train_file.xlsx
    outs:
      - data/processed/train.pkl