name: Lint with Ruff

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint with Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.email "$GIT_USER_EMAIL"
          git config --global user.name "$GIT_USER_NAME"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff check and correct 
        run: |
          ruff check --fix src/. --output-format=github
          ruff format src/.
          git config --global user.email "pavel.data@gmail.com"
          git config --global user.name "pavel.kokin"
          git add .
          git commit -m "Auto-fix with Ruff" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/kokinpavel/dste.git